#include "images.h"

const ext_img_desc_t images[27] = {
    { "dashboard_background", &img_dashboard_background },
    { "icon_abs_16", &img_icon_abs_16 },
    { "icon_airbag_16", &img_icon_airbag_16 },
    { "icon_battery_16", &img_icon_battery_16 },
    { "icon_brake_warning_16", &img_icon_brake_warning_16 },
    { "icon_check_engine_16", &img_icon_check_engine_16 },
    { "icon_coolant_16", &img_icon_coolant_16 },
    { "icon_high_beam_16", &img_icon_high_beam_16 },
    { "icon_oil_pressure_16", &img_icon_oil_pressure_16 },
    { "icon_rear_fog_16", &img_icon_rear_fog_16 },
    { "icon_seat_belt_16", &img_icon_seat_belt_16 },
    { "icon_tire_pressure_16", &img_icon_tire_pressure_16 },
    { "icon_traction_control_16", &img_icon_traction_control_16 },
    { "menu_defult_16", &img_menu_defult_16 },
    { "menu_vehicle_16", &img_menu_vehicle_16 },
    { "menu_trip_meter_16", &img_menu_trip_meter_16 },
    { "menu_driving_assistance_16", &img_menu_driving_assistance_16 },
    { "menu_fuel_level_16", &img_menu_fuel_level_16 },
    { "meunu_settings_16", &img_meunu_settings_16 },
    { "icon_seat_belt_24", &img_icon_seat_belt_24 },
    { "icon_brake_warning_24", &img_icon_brake_warning_24 },
    { "icon_parking_break_24", &img_icon_parking_break_24 },
    { "icon_coolant_24", &img_icon_coolant_24 },
    { "icon_high_beam_24", &img_icon_high_beam_24 },
    { "icon_check_engine_24", &img_icon_check_engine_24 },
    { "vehicle_truck", &img_vehicle_truck },
    { "bar_fuel", &img_bar_fuel },
};